### ISSUE TITLE
Hello B!

### ISSUE THREAD

**Issue by Fukuda-B** [abava00/githubtest#5]
Thank you for reviewing my code.
I'm sorry that the pull request didn't go through, but B is a god.

**Comment by AdmHatena** [comment]
????????????????????????????????????

**Comment by abava00** [comment]
HAHAHA
nice joke boy

**Comment by pacificbelt30** [comment]
チャットサービスと化したgithub君

**Comment by AdmHatena** [comment]
@pacificbelt30 discordより使い勝手いい説、あると思います。

**Comment by Fukuda-B** [comment]
□□□□□□□□
□■■■■□□□
□■□□□■□□
□■□□□■□□
□■■■■□□□
□■□□□■□□
□■□□□□■□
□■□□□□■□
□■■■■■□□
□□□□□□□□

**Comment by AdmHatena** [comment]
@Fukuda-B b is very very bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbad

**Comment by pacificbelt30** [comment]
Email notifications are depressing.

**Comment by Fukuda-B** [comment]
https://github.com/Fukuda-B/BBBot/blob/6a4ba45f7b8afbbf47351e307e6e589488eece2b/discordbot.py#L286

**Comment by AdmHatena** [comment]
githubbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb include B!
