### ISSUE TITLE
https://github.com/Fukuda-B/BBBot/blob/6a4ba45f7b8afbbf47351e307e6e589488eece2b/discordbot.py#L286

### ISSUE THREAD

**Issue by AdmHatena** [abava00/githubtest#6]
https://github.com/Fukuda-B/BBBot/blob/6a4ba45f7b8afbbf47351e307e6e589488eece2b/discordbot.py#L286

_Originally posted by @Fukuda-B in https://github.com/abava00/githubtest/issues/5#issuecomment-822978087_

**Comment by AdmHatena** [comment]
404 ... ...

**Comment by pacificbelt30** [comment]
not found …

**Comment by abava00** [comment]
END
